config/routes.rb
LauncherJournal::Application.routes.draw do
  root 'journal_entries#index'
  resources :journal_entries
  resources :categories
 

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :journal_categories,
    inverse_of: :category
  has_many :journal_entries,
    through: :journal_categories,
    inverse_of: :categories
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/journal_category.rb
class JournalCategory < ActiveRecord::Base
  belongs_to :journal_entry
  belongs_to :category

  validates_presence_of :category
  validates_presence_of :journal_entry
  validates_uniqueness_of :journal_entry_id, 
    scope: :category_id


end

app/models/journal_entry.rb
class JournalEntry < ActiveRecord::Base
  has_many :journal_categories,
    inverse_of: :journal_entry
  has_many :categories,
    through: :journal_categories,
    inverse_of: :journal_entries
  validates_presence_of :title
  validates_presence_of :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:succes] = "Success"
      redirect_to categories_path
    else
      flash[:error] = "Error man"
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
      redirect_to categories_path
    if @category.update_attributes(category_params)
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  def index
    @journal_entries = JournalEntry.all
    @categories = Category.all
  end

  def new
    @journal_entry = JournalEntry.new
  end

  def create
    @journal_entry = JournalEntry.new(journal_params)
    if @journal_entry.save
    binding.pry
      flash[:success] = "Success"
      redirect_to journal_entries_path
    else
      flash[:error] = "Error"
      render :new
    end
  end

  def destroy
    @journal_entry = JournalEntry.find(params[:id])
    if @journal_entry.destroy
      flash[:success] = "Deleted successfully"
      redirect_to journal_entries_path
    end
  end

  private
  def journal_params
    params.require(:journal_entry).permit(:title, :description, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/views/categories/edit.html.erb
<h1> Editing Post </h1>
<%= render 'shared/form' %>

app/views/categories/index.html.erb
<h1> Categories </h1>

<ol>
  <% @categories.each do |category| %>
    <li>
      <%= category.name %>
      <%= link_to 'Edit', edit_category_path(category.id) %>
      <%= link_to 'Delete', category_path(category.id), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
    <br>
  <% end %>
</ol>

  <%= link_to 'create category', new_category_path %>

app/views/categories/new.html.erb
<% if @category.errors.full_messages.any? %>
  <% @category.errors.full_messages.each do |error_message| %>
    <%= error_message %><br>
  <% end %>
<% end %>

<%= form_for(@category) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.submit %>
<% end %>

app/views/journal_entries/index.html.erb
<h1> All Entries </h1>
<%= link_to 'new post', new_journal_entry_path %>
<br>
<table>
  <tr>
    <td><h3>Title</h3></td>
    <td><h3>Description</h3></td>
    <td><h3>Created At</h3></td>
  </tr>

  <% @journal_entries.each do |entry| %>
    <tr>
      <td><%= entry.title %></td>
      <td><%= entry.description %></td>
      <td><%= entry.created_at %></td>
      <td><%= link_to "Delete", journal_entry_path(entry), method: :delete, confirm: "Are you sure?" %></td>
    </tr>
  <% end %>
</table>

app/views/journal_entries/new.html.erb
<% if @journal_entry.errors.full_messages.any? %>
  <% @journal_entry.errors.full_messages.each do |error_message| %>
    <%= error_message %><br>
  <% end %>
<% end %>

<%= form_for(@journal_entry) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :description %>
  <%= f.text_area :description %><br>

  <%= select(:journal_categories, :category_id, options_for_select([Category.all])).save %>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LauncherJournal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <%= link_to 'Categories', categories_path %> |
    <%= link_to 'Journal Entries', root_path %>

    <% flash.each do |key, value| %>
      <div class= "alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_form.html.erb
<% if @category.errors.full_messages.any? %>
  <% @category.errors.full_messages.each do |error_message| %>
    <%= error_message %><br>
  <% end %>
<% end %>

<%= form_for(@category) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.submit %>

<% end %>